# vim: et:ts=4:sw=4
version: '2'
services:
    frontend:
        image: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/storage/repos/docker-config/nginx/ssl:/etc/nginx/ssl:ro"
            - "/storage/repos/docker-config/nginx/conf.d:/etc/nginx/conf.d:ro"
            - "/storage/mac/munki_repo:/srv/munki_repo:ro"
    unifi:
        image: rednut/unifi-controller:v5.2.7
        build:
            context: https://github.com/overhacked/docker-unifi-controller.git#unifi5
        restart: always
        ports:
            - "8080:8080" # INFORM
            - "3478:3478/udp" # STUN
        volumes:
            - /storage/unifi-data:/usr/lib/unifi/data
    transmission:
        image: linuxserver/transmission
        restart: always
        ports:
            - "9091:9091"
            - "51413:51413"
            - "51413:51413/udp"
        volumes:
            - "/storage/repos/docker-config/transmission:/config"
            - "/storage/export/downloads:/downloads"
            - "/storage/export/downloads/torrents:/watch"
        environment:
            - TZ="America/New_York"

    opennms:
        image: opennms/all:latest
        environment:
            - DB_POSTGRES_PASSWORD=fhdj443%Ax
        volumes:
            - "/storage/opennms/log:/var/log/opennms"
            - "/storage/opennms/data:/var/opennms"
        ports:
            - "8980:8980" # HTTP
            - "18980:18980" # JMX
            - "1099:1099" # KARAF RMI
            - "8101:8101" # KARAF SSH
            - "61616:61616" # MQ
            - "5432:5432" # PostgreSQL
            - "161:161" # SNMP Agent
            - "162:162" # SNMP Server
        stdin_open: true
        tty: true
