version: '2'
services:
    frontend:
        image: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/storage/repos/docker-config/nginx/ssl:/etc/nginx/ssl:ro"
            - "/storage/repos/docker-config/nginx/conf.d:/etc/nginx/conf.d:ro"
    unifi:
        image: rednut/unifi-controller:v5.2.7
        build:
            context: https://github.com/overhacked/docker-unifi-controller.git#unifi5
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - /storage/unifi-data:/usr/lib/unifi/data
    transmission:
        image: linuxserver/transmission
        restart: always
        ports:
            - "9091:9091"
            - "51413:51413"
            - "51413:51413/udp"
        volumes:
            - "/storage/repos/docker-config/transmission:/config"
            - "/storage/export/downloads:/downloads"
            - "/storage/export/downloads/torrents:/watch"
        environment:
            - TZ="America/New_York"

