# vim: et:ts=4:sw=4
version: '2'
services:
    frontend:
        image: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/storage/conf/docker/nginx/ssl:/etc/nginx/ssl:ro"
            - "/storage/conf/docker/nginx/conf.d:/etc/nginx/conf.d:ro"
            - "/storage/conf/docker/nginx/htpasswd:/etc/nginx/htpasswd:ro"
            - "/storage/mac/munki_repo:/srv/munki_repo:ro"
            - "/storage/conf/docker/wpad:/srv/wpad:ro"
    unifi:
        image: rednut/unifi-controller
        build:
            context: https://github.com/overhacked/docker-unifi-controller.git#v5.4.9-RC
        restart: always
        ports:
            - "8080:8080" # INFORM
            - "3478:3478/udp" # STUN
        volumes:
            - /storage/data/unifi:/usr/lib/unifi/data
    transmission:
        image: linuxserver/transmission
        restart: always
        ports:
            - "9091:9091"
            - "51413:51413"
            - "51413:51413/udp"
        volumes:
            - "/storage/conf/docker/transmission:/config"
            - "/storage/export/downloads:/downloads"
            - "/storage/export/downloads/torrents:/watch"
        environment:
            - TZ="America/New_York"
    zabbix-db:
        image: monitoringartist/zabbix-db-mariadb
        volumes:
            - /storage/data/zabbix:/var/lib/mysql
            - /storage/backup/docker/zabbix:/backups
            - /etc/localtime:/etc/localtime:ro
        environment:
            - MARIADB_USER=zabbix
            - MARIADB_PASS=otWocnv4fmeA3r
    zabbix-server:
        image: monitoringartist/zabbix-xxl:latest
        depends_on:
            - zabbix-db
        ports:
            - "10051:10051"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /storage/conf/docker/zabbix/etc/snmp:/etc/snmp:ro
            - /storage/conf/docker/zabbix/mibs:/usr/share/snmp/mibs:ro
        links:
            - zabbix-db:zabbix.db
        environment:
            - ZS_DBHost=zabbix.db
            - ZS_DBUser=zabbix
            - ZS_DBPassword=otWocnv4fmeA3r
    reposado:
        #image: macadmins/reposado
        build:
            context: https://github.com/overhacked/docker-reposado.git#uwsgi-nginx
        restart: always
        environment:
            - LOCALCATALOGURLBASE="https://updates.manyfoldfarm.com:443"
        volumes:
            - /storage/mac/swupdate/html:/reposado/html
            - /storage/mac/swupdate/metadata:/reposado/metadata
            - /storage/conf/docker/reposado/preferences.plist:/reposado/code/preferences.plist
    gitlist:
        image: davibe/gitlist-docker
        restart: always
        volumes:
            - /storage/repos:/repos
