# vim: et:ts=4:sw=4
version: '2'
services:
    frontend:
        image: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/storage/conf/docker/nginx/ssl:/etc/nginx/ssl:ro"
            - "/storage/conf/docker/nginx/conf.d:/etc/nginx/conf.d:ro"
            - "/storage/conf/docker/nginx/htpasswd:/etc/nginx/htpasswd:ro"
            - "/storage/mac/munki_repo:/srv/munki_repo:ro"
            - "/storage/conf/docker/wpad:/srv/wpad:ro"
            - "/storage/backup/tcpdump:/tcpdump:rw"
    unifi:
        image: rednut/unifi-controller
        build:
            context: https://github.com/overhacked/docker-unifi-controller.git#v5.4.9-RC
        restart: always
        ports:
            - "8080:8080" # INFORM
            - "3478:3478/udp" # STUN
        volumes:
            - /storage/data/unifi:/usr/lib/unifi/data
    transmission:
        image: overhacked/transmission-openvpn
        build: ./transmission/build
        privileged: true
        restart: always
#       ports:
#           - "51413:51413"
#           - "51413:51413/udp"
        dns:
            - 8.8.8.8
            - 8.8.4.4
        volumes:
            - "/storage/conf/docker/transmission/conf:/data/transmission-home"
            - "/storage/export/downloads:/data"
#           - "/storage/export/downloads/torrents:/watch"
            - "/etc/localtime:/etc/localtime:ro"
        environment:
#           - TZ="America/New_York"
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_USERNAME=p4995968
            - OPENVPN_PASSWORD=JsJTPa9nFY
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - LOCAL_NETWORK=10.30.0.0/16
            - TRANSMISSION_WATCH_DIR="/data/torrents"
    zabbix-db:
        image: monitoringartist/zabbix-db-mariadb
        restart: always
        volumes:
            - /storage/data/zabbix:/var/lib/mysql
            - /storage/backup/docker/zabbix:/backups
            - /etc/localtime:/etc/localtime:ro
        environment:
            - MARIADB_USER=zabbix
            - MARIADB_PASS=otWocnv4fmeA3r
    zabbix-server:
        image: monitoringartist/zabbix-xxl:latest
        restart: always
        depends_on:
            - zabbix-db
        ports:
            - "10051:10051"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /storage/conf/docker/zabbix/etc/snmp:/etc/snmp:ro
            - /storage/conf/docker/zabbix/mibs:/usr/share/snmp/mibs:ro
        links:
            - zabbix-db:zabbix.db
        environment:
            - ZS_DBHost=zabbix.db
            - ZS_DBUser=zabbix
            - ZS_DBPassword=otWocnv4fmeA3r
    reposado:
        #image: macadmins/reposado
        build:
            context: https://github.com/overhacked/docker-reposado.git#uwsgi-nginx
        restart: always
        environment:
            - LOCALCATALOGURLBASE="https://updates.manyfoldfarm.com:443"
        volumes:
            - /storage/mac/swupdate/html:/reposado/html
            - /storage/mac/swupdate/metadata:/reposado/metadata
            - /storage/conf/docker/reposado/preferences.plist:/reposado/code/preferences.plist
    gitlist:
        image: davibe/gitlist-docker
        restart: always
        volumes:
            - /storage/repos:/repos
    ntop:
        build: ./ntopng/build
        image: overhacked/ntopng-nprobe:latest
        restart: always
        ports:
            - "2055:2055/udp"
        volumes:
            - "/storage/conf/docker/ntopng/conf:/etc/ntopng:ro"
            - "/storage/conf/docker/ntopng/data:/var/lib/redis:rw"
    mongo-db:
        image: "mongo:3"
        restart: always
        volumes:
            - /storage/data/graylog/mongo:/data/db
    elasticsearch-graylog:
        image: "elasticsearch:2"
        restart: always
        volumes:
            - /storage/data/graylog/elasticsearch:/usr/share/elasticsearch/data
        command: "elasticsearch -Des.cluster.name='graylog'"
    graylog:
        image: graylog2/server:2.1.2-1
        restart: always
        volumes:
            - /storage/data/graylog/journal:/usr/share/graylog/data/journal
            - /storage/conf/graylog:/usr/share/graylog/data/config
        environment:
            - GRAYLOG_SERVER_JAVA_OPTS=-Xmx4096m
        links:
            - mongo-db:mongo
            - elasticsearch-graylog:elasticsearch
        ports:
            - "9000:9000"
            - "12201/udp:12201/udp"
            - "1514-1524:1514-1524/udp"
