# vim: et:ts=4:sw=4
version: '2.3'
services:
    frontend:
        image: nginx:mainline-alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "${CONFIG_ROOT:-.}/nginx/ssl:/etc/nginx/ssl:ro"
            - "${CONFIG_ROOT:-.}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "${CONFIG_ROOT:-.}/nginx/conf.d:/etc/nginx/conf.d:ro"
            - "${CONFIG_ROOT:-.}/nginx/htpasswd:/etc/nginx/htpasswd:ro"
            - "/storage/mac/munki_repo:/srv/munki_repo:ro"
            - "${CONFIG_ROOT:-.}/wpad:/srv/wpad:ro"
            - "/storage/data/httpd:/srv/data"
            - "/storage/backup/tcpdump:/tcpdump:rw"
            - "/var/cache/nginx"
        logging:
            driver: gelf
            options:
                gelf-address: ${GELF_TARGET}
        networks:
            default:
                ipv4_address: 172.16.243.254
                ipv6_address: 2001:559:80e5:d0:cc::fe
    bind:
        image: overhacked/bind-dnssec-slave
        build: https://github.com/overhacked/bind-DNSSEC-slave.git#overhacked
        restart: always
        ports:
            - "${EXTERNAL_IP:-0.0.0.0}:53:53/udp"
            - "${EXTERNAL_IP:-0.0.0.0}:53:53"
        volumes:
            - "${CONFIG_ROOT:-.}/bind-slave/conf/named.conf:/etc/bind/named.conf.local:ro"
        logging:
            driver: gelf
            options:
                gelf-address: ${GELF_TARGET}
        networks:
            default:
                ipv4_address: 172.16.243.250
                ipv6_address: 2001:559:80e5:d0:cc::53
    smtp:
        image: wader/postfix-relay
        build: https://github.com/overhacked/postfix-relay.git#overhacked
        restart: always
        ports:
            - "25:25"
        volumes:
            - "${CONFIG_ROOT:-.}/postfix/dkim-keys:/etc/opendkim/keys"
            - "${CONFIG_ROOT:-.}/postfix/ssl:/etc/postfix/ssl:ro"
            - "${CONFIG_ROOT:-.}/postfix/opendkim.conf:/etc/opendkim.conf:ro"
            - /var/lib/postfix
            - /var/spool/postfix
            - /var/mail
        environment:
            POSTFIX_myhostname: mail.sineya.org
            POSTFIX_mydestination: localhost, zee, zee.edge.manyfoldfarm.com, mail, mail.sineya.org
            POSTFIX_mynetworks: 127.0.0.0/8 172.16.243.0/24 10.30.0.0/16 50.207.215.128/27 [2001:559:80e5::]/48
            POSTFIX_smtp_bind_address: 50.207.215.133
            POSTFIX_smtp_bind_address6: 2001:559:80e5:ed:d0::133
            POSTFIX_smtp_tls_security_level: may
            POSTFIX_smtpd_tls_security_level: may
            POSTFIX_smtpd_tls_cert_file: /etc/postfix/ssl/server.crt
            POSTFIX_smtpd_tls_key_file: /etc/postfix/ssl/server.key
            OPENDKIM_DOMAINS: manyfoldfarm.com sineya.org
        logging:
            driver: gelf
            options:
                gelf-address: ${GELF_TARGET}
        networks:
            rackvlan:
                ipv4_address: 50.207.215.133
                ipv6_address: 2001:559:80e5:ed:d0::133
            default:
                # Include the below addresses in /etc/hosts on the Docker host
                # machine(s), as macvlan addresses are not reachable from the host:
                # <https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/virtualization_host_configuration_and_guest_installation_guide/app_macvtap>
                # AND <https://stackoverflow.com/questions/44048915/unable-to-access-docker-containers-from-host-over-macvlan-network>
                ipv4_address: 172.16.243.253
                ipv6_address: 2001:559:80e5:d0:cc::25
    unifi:
        image: overhacked/unifi:latest
        build:
            #context: https://github.com/overhacked/docker-unifi-controller.git
            context: unifi/build
            args:
                UNIFI_VERSION: 5.6.19
        restart: always
        ports:
            - "8080:8080" # INFORM
            - "3478:3478/udp" # STUN
        volumes:
            - /storage/data/unifi:/usr/lib/unifi/data
        cpu_shares: 512
        logging:
            driver: gelf
            options:
                gelf-address: ${GELF_TARGET}
#    transmission:
#        image: overhacked/transmission-openvpn
#        build: https://github.com/overhacked/docker-transmission-openvpn.git#overhacked
#        privileged: true
#        restart: always
##       ports:
##           - "51413:51413"
##           - "51413:51413/udp"
#        dns:
#            - 8.8.8.8
#            - 8.8.4.4
#        volumes:
#            - /data/transmission-home
#            - "/storage/export/downloads:/data"
#            - "/etc/localtime:/etc/localtime:ro"
#        environment:
#            - OPENVPN_PROVIDER=PIA
#            - OPENVPN_USERNAME=p4995968
#            - OPENVPN_PASSWORD=JsJTPa9nFY
#            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
#            - LOCAL_NETWORK=10.30.0.0/16
#            - TRANSMISSION_WATCH_DIR=/data/torrents
#            - TRANSMISSION_DOWNLOAD_DIR=/data/completed
#            - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES='true'
    zabbix-db:
        image: monitoringartist/zabbix-db-mariadb
        restart: always
        volumes:
            - /storage/data/zabbix:/var/lib/mysql
            - /storage/data/zabbix/ib_log:/var/lib/mysql/ib_log
            - /storage/backup/docker/zabbix:/backups
            - /etc/localtime:/etc/localtime:ro
            - /storage/conf/zabbix-db/etc/custom-config:/etc/custom-config:ro
        environment:
            - MARIADB_USER=zabbix
            - MARIADB_PASS=otWocnv4fmeA3r
        logging:
            driver: gelf
            options:
                gelf-address: ${GELF_TARGET}
    zabbix-server:
        image: monitoringartist/dockbix-xxl:3.4.4
        restart: always
        depends_on:
            - zabbix-db
        ports:
            - "10051:10051"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIG_ROOT:-.}/zabbix/etc/snmp:/etc/snmp:ro
            - ${CONFIG_ROOT:-.}/zabbix/mibs:/usr/share/snmp/mibs:ro
            - ${CONFIG_ROOT:-.}/zabbix/modules:/usr/lib/zabbix/modules:ro
            - ${CONFIG_ROOT:-.}/zabbix/alertscripts:/usr/local/share/zabbix/alertscripts:ro
            - ${CONFIG_ROOT:-.}/zabbix/externalscripts:/usr/local/share/zabbix/externalscripts:ro
            - ${CONFIG_ROOT:-.}/zabbix/etc/nginx/hosts.d/default.conf:/etc/nginx/hosts.d/default.conf:ro
            - "/storage/backup/tcpdump:/tcpdump:rw"
        environment:
            - ZS_DBHost=zabbix-db
            - ZS_DBUser=zabbix
            - ZS_DBPassword=otWocnv4fmeA3r
            - ZS_Timeout=18
            - ZS_StartDiscoverers=2
            - ZS_StartPollers=8
            - ZS_StartPingers=3
            - ZS_StartIPMIPollers=1
            - ZS_AlertScriptsPath=/usr/local/share/zabbix/alertscripts
            - ZS_ExternalScripts=/usr/local/share/zabbix/externalscripts
            - ZS_LoadModulePath=/usr/lib/zabbix/modules
            - ZS_LoadModule_1=libzbxmodbus.so
            #- ZS_LoadModule_2=unifi.so
            - ZS_ValueCacheSize=128M
            - "XXL_api=false"
            - "XXL_zapix=true"
            - "XXL_grapher=true"
            - "XXL_searcher=false"
            - "XXL_analytics=false"
        logging:
            driver: gelf
            options:
                gelf-address: ${GELF_TARGET}
        networks:
            default:
                ipv4_address: 172.16.243.251
                ipv6_address: 2001:559:80e5:d0:cc::5b
    zabbix-monitor:
        image: overhacked/zabbix-monitor:latest
        build:
            context: zabbix-monitor/build
            args:
                ZM_GIT_REPO: https://github.com/overhacked/zabbix-monitor.git
                ZM_GIT_BRANCH: overhacked
        restart: always
    zabbix-infinias:
        image: overhacked/iaevents-listener:latest
        restart: always
        build:
            context: zabbix-infinias/build
        init: true
        environment:
            INF_ZABBIX_SERVER: zabbix-server
            INF_ZABBIX_HOSTNAME: access.sec.res.sineya.org
        ports:
            - "5556:8080"
    zabbix-solar:
        image: overhacked/solar-poller:latest
#build: https://github.com/overhacked/docker-solar-poller.git
        build: ./solar-poller/build
        restart: always
        depends_on:
            - zabbix-server
        environment:
            SP_EGAUGE_URI: http://zabbix:zabbix@solar-gauge.res.sineya.org/cgi-bin/egauge?v1&inst&tot
            SP_ZABBIX_SERVER: zabbix-server
    unifi-miner:
        image: overhacked/unifi-miner-proxy:latest
        restart: always
        build: unifi/build-miner-proxy
        ports:
            - "8448:8448"
        cpu_shares: 256
        environment:
            MINER_UniFiLocation: https://unifi:8443
            MINER_UniFiVersion: v5
            MINER_UniFiUser: stat
            MINER_UniFiPass: stat
            MINER_DebugLevel: 1
            MINER_SiteName: nx4d875m
#        logging:
#            driver: journald
#            options:
#                tag: unifi-miner
    reposado:
        #image: macadmins/reposado
        build:
            context: https://github.com/overhacked/docker-reposado.git#uwsgi-nginx
        restart: always
        environment:
            - LOCALCATALOGURLBASE="https://updates.manyfoldfarm.com:443"
        volumes:
            - /storage/mac/swupdate/html:/reposado/html
            - /storage/mac/swupdate/metadata:/reposado/metadata
            - ${CONFIG_ROOT:-.}/reposado/preferences.plist:/reposado/code/preferences.plist
    gitlist:
        image: davibe/gitlist-docker
        restart: always
        volumes:
            - /storage/repos:/repos
#    nfsen:
#        build: ./nfsen/build
#        image: overhacked/nfsen:latest
#        restart: always
#        ports:
#            - "2055:2055/udp"
#        environment:
#            TZ: America/New_York
#            LOGLEVEL: 6
#        volumes:
#            - "/storage/data/nfsen/profiles-data:/data/nfsen/profiles-data:rw"
#            - "/storage/stat/nfsen/profiles-stat:/stat/nfsen/profiles-stat:rw"
#        logging:
#            driver: gelf
#            options:
#                gelf-address: ${GELF_TARGET}
#    ntop:
#        build: ./ntopng/build
#        image: overhacked/ntopng-nprobe:latest
#        restart: always
#        ports:
#            - "2055:2055/udp"
#        volumes:
#            - "${CONFIG_ROOT:-.}/ntopng/conf:/etc/ntopng:ro"
#            - "${CONFIG_ROOT:-.}/ntopng/data:/var/lib/redis:rw"
#        logging:
#            driver: gelf
#            options:
#                gelf-address: ${GELF_TARGET}
    mongo-db:
        image: "mongo:3.4.4"
        # Keep the cache size very low, because this is mostly a write-only DB
        # Reads only happen when stats queries are made via UniFi controller,
        # and we don't mind if those are a bit slow
        command: "mongod --wiredTigerCacheSizeGB 1.0"
        restart: always
        volumes:
            - /storage/data/graylog/mongo:/data/db
    elasticsearch-graylog:
        image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.4"
        restart: always
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 10g
        environment:
            cluster.name: graylog
            bootstrap.memory_lock: "true"
            http.host: 0.0.0.0
            transport.host: localhost
            network.host: 0.0.0.0
            xpack.security.enabled: "false"
            ES_JAVA_OPTS: -Xms8g -Xmx8g
        volumes:
            - /storage/data/graylog/elasticsearch:/usr/share/elasticsearch/data
    graylog:
        image: graylog2/server:2.3.2-2
        restart: always
        volumes:
            - /storage/data/graylog/journal:/usr/share/graylog/data/journal
            - /storage/conf/graylog:/usr/share/graylog/data/config:ro
            #- /storage/data/graylog/plugin/graylog-plugin-netflow-0.1.1.jar:/usr/share/graylog/plugin/graylog-plugin-netflow-0.1.1.jar:ro
        mem_limit: 6g
        environment:
            - GRAYLOG_SERVER_JAVA_OPTS=-Xmx4096m
        links:
            - mongo-db:mongo
            - elasticsearch-graylog:elasticsearch
        ports:
            - "12201-12202:12201-12202/udp"
            - "1514-1524:1514-1524/udp"
networks:
    default:
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
            - subnet: 172.16.243.0/24
              gateway: 172.16.243.1
            - subnet: 2001:559:80e5:d0:cc::/80
              gateway: 2001:559:80e5:d0:cc::1
    rackvlan:
        driver: macvlan
        enable_ipv6: true
        driver_opts:
            parent: ${EXTERNAL_IF}
        ipam:
            config:
                - subnet: 50.207.215.128/29
                  gateway: 50.207.215.129
                  ip_range: 50.207.215.132/30
                  aux_addresses:
                    # Prevent Jonathan's address from being handed out
                    jonathan: 50.207.215.132
                - subnet: 2001:559:80e5:ed::/64
                  gateway: 2001:559:80e5:ed::1
                  ip_range: 2001:559:80e5:ed:d0::/80
